#%RAML 1.0 Trait
queryParameters:
      movieID:
        displayName: movieID
        type: integer
        description: Get movie based on Movie ID
        example:
          1111
        required: false